-- Generated by nwg-displays on 2026-07-03 at 22:08:45. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@165.01",
    position = "7680x2224",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@74.78",
    position = "5120x1864",
    scale = 1.0
})
