-- Generated by nwg-displays on 2026-08-13 at 00:16:39. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@165.01",
    position = "2560x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@59.95",
    position = "0x0",
    scale = 1.0
})
