-- Colours generated by wallust.
-- wallust/wallust-hyprland.conf stays in hyprlang: wallust rewrites it on
-- every wallpaper change, and hyprlock.conf sources the same file.

local util = require("lua/util")

local vars = util.read_vars(util.HYPR .. "/wallust/wallust-hyprland.conf")

-- Fallbacks for a first boot before wallust has run.
local fallback = {
    background = "rgb(17181C)",
    foreground = "rgb(E4ECF2)",
    color0 = "rgb(3E3F43)",
    color10 = "rgb(202D4F)",
    color12 = "rgb(6582AB)",
    color15 = "rgb(D0DBE5)",
}

return setmetatable(vars, {
    __index = function(_, key)
        return fallback[key] or "rgb(595959)"
    end,
})
